import About from "@/components/about/About";
import Contact from "@/components/contact/Contact";
import Calender from "@/components/github/Calender";
import Navbar from "@/components/navbar/Navbar";
import Projects from "@/components/projects/Projects";
import Skills from "@/components/skills/Skills";
import Home from "@/components/home/Home";
import Head from "next/head";
import Footer from "@/components/footer/Footer";

export default function App() {
  return (
    <>
      <Head>
        <title>Ahmad Khan&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/favicon.ico" />
      </Head>
      <Navbar />
      <Home />
      <About />
      <Skills />
      <Calender />
      <Projects />
      <Contact />
      <Footer />
    </>
  );
}
